name: Build

on:
  workflow_call:
    inputs:
      shouldRunKmp:
        required: true
        type: string
      shouldRunAndroid:
        required: true
        type: string
      shouldRunIos:
        required: true
        type: string
      shouldRunDesktop:
        required: true
        type: string

jobs:
  Android:
    if: ${{ inputs.shouldRunKmp == 'true' || inputs.shouldRunAndroid == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Job set up
        uses: ./.github/actions/job-set-up

      - run: ./gradlew :app:android:assemble

  Desktop:
    if: ${{ inputs.shouldRunKmp == 'true' || inputs.shouldRunDesktop == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Job set up
        uses: ./.github/actions/job-set-up

      - run: ./gradlew :app:desktop:assemble

  Web:
    if: ${{ inputs.shouldRunKmp == 'true' || inputs.shouldRunWeb == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Job set up
        uses: ./.github/actions/job-set-up

      - run: ./gradlew :app:web:jsBrowserDevelopmentRun

  iOS:
    if: ${{ inputs.shouldRunKmp == 'true' || inputs.shouldRunIos == 'true' }}
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v4

      - name: Job set up
        uses: ./.github/actions/job-set-up

      - name: iOS set up
        uses: ./.github/actions/ios-set-up

      - run: |
          cd app/ios
      - run: xcodebuild build -workspace ios/ios.xcworkspace -configuration Debug -scheme ios -sdk iphoneos -destination name='iPhone 14' -verbose
